swagger: '2.0'
info:
  description: |
    应用场景当交易发生之后一段时间内，由于买家或者卖家的原因需要退款时，卖家可以通过退款接口将支付款退还给买家，微信支付将在收到退款请求并且验证成功之后，按照退款规则将支付款按原路退到买家帐号上。注意：1.交易时间超过一年的订单无法提交退款；2、微信支付退款支持单笔交易分多次退款，多次退款需要提交原支付订单的商户订单号和设置不同的退款单号。申请退款总金额不能超过订单金额。 一笔退款失败后重新提交，请不要更换退款单号，请使用原商户退款单号。3、每个支付订单的部分退款次数不能超过 50 次
  version: 1.0.1
  title: 申请退款
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: api.mch.weixin.qq.com
basePath: /qsv3
schemes:
  - "https"
security:
  - ApiKeyAuth: []
paths:
  /refunds:
    post:
      tags:
        - "overseas"
        - "refund"
        
      summary: ""
      description: |
        
      operationId: CreateRefunds
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: payload
          required: true
          schema:
            $ref: '#/definitions/reqalias'
      responses:
        200:
          description: "处理成功"
          schema:
            $ref: "#/definitions/respalias"
        default:
          description: "处理失败"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /refunds/{refund_id}:
    get:
      tags:
        - "refund"
        
      summary: "查询单笔退款"
      description: |
        提交退款申请后，通过调用该接口查询退款状态。退款有一定延时，用零钱支付的退款 20 分钟内到账，银行卡支付的退款 3 个工作日后重新查询退款状态。
      operationId: GetRefunds
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: acquiring_bank_id
          in: query
          description: 微信支付分配给从业机构的机构号
          required: true
          type: string
          format: email
        - name: merchant_id
          in: query
          description: 从业机构报备的商户返回的商户识别码
          required: true
          type: string
        - name: channel_id
          in: query
          description: 微信支付分配给收单服务商的 ID
          required: true
          type: string
        - name: refund_id
          in: path
          description: 微信退款单号
          required: true
          type: string
      responses:
        200:
          description: "处理成功"
          schema:
            $ref: "#/definitions/RefundGetResponse"
        default:
          description: "处理失败"
          schema:
            $ref: "#/definitions/ErrorResponse"
  
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization
definitions:
  ErrorResponse:
    title: "错误应答"
    description: "错误应答"
    type: "object"
    properties:
      code:
        description: "详细错误码"
        type: string
        example: "PARAM_ERROR"
      message:
        description: "错误描述，使用易理解的文字表示错误的原因"
        type: string
        example: "Invalid schema: #/description. Invalid keyword: maxByteLength"
      detail:
        type: object
        properties:
          field:
            description: "指示错误参数的位置。当错误参数位于请求body的JSON时，填写指向参数的JSON Pointer。当错误参数位于请求的url或者querystring时，填写参数的变量名"
            type: string
            example: "#/description"
          value:
            description: "错误的值"
            type: string
            example: "长长长长长长长长长长长长长长长长字符串"
          issue:
            description: "具体错误原因"
            type: string
            example: "参数错误"
          location:
            description: "错误参数所处位置"
            type: string
            example: "body"
        required:
          - field
          - issue
    required:
      - code
      - message
  reqalias:
    title: reqalias文档标题
    description: reqalias文档描述
    type: "object"
    properties:
      out_trade_no:
        title: 商户订单号
        description: 原支付交易对应的订单号
        example: 1217752501201407033233 
        type: string
        minLength: 0
      out_refund_no:
        title: 商户退款单号
        description: 商户系统内部的退款单号，商户系统内部唯一，只能是数字、大小写字母_-|*@ ，同一 退款单号多次请求只退一笔。
        example: 1217752501201407033233 
        type: string
        minLength: 0
      currency:
        title: 货币类型
        description: 符合 ISO 4217 标准的三位字母代码，目前 只支持人民币：CNY
        example: CNY 
        type: string
        minLength: 0
        maxLength: 10
      refund:
        title: 退款金额
        description: 退款金额，单位为分，只能为整数，不能超 过原订单支付金额，如果有使用券，后台会 按比例退。
        example: 888 
        type: integer
      total:
        title: 原订单金额
        description: 原支付交易的订单总金额，单位为分，只能 为整数，详见支付金额
        example: 888 
        type: integer
      acquiring_bank_id:
        title: 从业机构号
        description: 微信支付分配给从业机构的机构号
        example: 1900000100 
        type: string
      appid:
        title: 从业机构号
        description: 微信支付分配给从业机构的机构号
        example: 1900000100 
        type: string
      merchant_id:
        title: 特约商户号
        description: 从业机构报备的商户返回的商户识别码
        example: 1900000109 
        type: string
      merchant_appid:
        title: 特约商户 APPID
        description: appid 是商户在微信申请公众号成功后分配 的帐号 ID，需要机构侧有配置绑定关系才 能传
        example: wx8888888888888888 
        type: string
      zq_mch_code:
        title: 转清商户号
        description: 验签后获得
        example: 1900000151 
        type: string
      channel_id:
        title: 服务商号
        description: 微信支付分配给收单服务商的 ID
        example: 19000001 
        type: string
      reason:
        title: 退款原因
        description: 若商户传入，会在下发给用户的退款消息中 体现退款原因
        example: 商品已售完 
        type: string
      source:
        title: 退款资金来源
        description: REFUND_SOURCE_UNSETTLED_FUNDS--- 未结算资金退款（默认使用未结算资金退 款） REFUND_SOURCE_RECHARGE_FUNDS--- 可用余额退款
        example: REFUND_SOURCE_UNSETTLED_FUNDS 
        type: string
      attach:
        title: 附加信息
        description: 附加信息
        example: 附加信息附加信息附加信息 
        type: string
      refund_notify_url:
        title: 退款回调地址
        description: 退款回调地址
        example: https://abc.com 
        type: string
  respalias:
    title: respalias文档标题
    description: respalias文档描述
    type: "object"
    properties:
      id:
        title: 微信支付退款 订单号
        description: 微信支付退款订单号
        example:  
        type: string
      out_refund_no:
        title: 商户退款单号
        description: 返回的退款订单号。
        example:  
        type: string
      currency:
        title: 货币类型
        description: 符合 ISO 4217 标准的三位字母代码，目前 只支持人民币：CNY
        example: CNY
        type: string
      refund:
        title: 退款金额
        description: 退款金额，单位为分，只能为整数，不能超 过原订单支付金额，如果有使用券，后台会 按比例退。
        example:  
        type: integer
      discount_refund:
        title: 优惠退款金 额
        description: 代金券/满立减等退款金额
        example:  
        type: integer
      payer_refund:
        title: 用户退款金 额
        description: 退款给用户的金额，不包含所有优惠券金额
        example:  
        type: integer
      settlement_refund:
        title: 无
        description: 无
        example:  
        type: integer
      detail:
        title: 优惠退款详情
        description: 优惠退款功能信息，详细说明见下文
        type: array
 
        items:
          $ref: '#/definitions/Detail'
      create_time:
        title: 退款创建时间
        description: 退款受理时间
        example:  
        type: string
  RefundGetRequest:
    title: 
    description: 
    type: "object"
    properties:
      acquiring_bank_id:
        title: 从业机构号
        description: 微信支付分配给从业机构的机构号
        example: 1900000100 
        type: string
        format: email
      merchant_id:
        title: 特约商户号
        description: 从业机构报备的商户返回的商户识别码
        example: 1900000109 
        type: string
      channel_id:
        title: 服务商号
        description: 微信支付分配给收单服务商的 ID
        example: 19000001 
        type: string
      refund_id:
        title: 微信退款单号
        description: 微信退款单号
        example:  
        type: string
    required:
      - acquiring_bank_id
      - merchant_id
      - channel_id
      - refund_id
  RefundGetResponse:
    title: 
    description: 
    type: "object"
    properties:
      unnamed_field_1:
        title: 
        description: 
        example:  
        type: integer
  Detail:
    title: 单品信息
    description: 单品信息
    type: "object"
    properties:
      promotion_id:
        title: 券 ID
        description: 券或者立减优惠 id
        example: 109519 
        type: string
        minLength: 0
      scope:
        title: 优惠范围
        description: GLOBAL- 全场代金券 SINGLE- 单品优惠
        example: SINGLE 
        type: string
        minLength: 0
      type:
        title: 优惠类型
        description: COUPON- 代金券，需要走结算资金的充值 型代金券,（境外商户券币种与支付币种一 致） DISCOUNT- 优惠券，不走结算资金的免充 值型优惠券，（境外商户券币种与标价币种 一致
        example: DISCOUNT 
        type: string
        minLength: 0
      amount:
        title: 优惠券面额
        description: 用户享受优惠的金额（优惠券面额=微信出 资金额+商家出资金额+其他出资方金额 ）
        example: 5 
        type: integer
        minLength: 0
      refund_amount:
        title: 优惠券退款 额
        description: 按比例退款的优惠券金额
        example: 5 
        type: integer
        maximum: 100
